baseURL = "https://2bcoma.github.io"
languageCode = "en-us"
title = "2bcoma dev"
theme = "main"
copyright = "2bcoma"

[params]
  avatar = "img/2bcomalogo.png"

[[menu.main]]
  name = "Home"
  url = "/"

[[menu.main]]
  name = "Our Apps"
  url = "/apps"

[[menu.main]]
  name = "Privacy Policy"
  url = "/policy"

[[params.social]]
  name = "instagram"
  url = "https://instagram.com/2bcoma?igshid=mm9sg7ctjx0m"

[[params.social]]
  name = "github"
  url = "https://github.com/2bcoma"

[[params.social]]
  name = "email"
  url = "mailto:2bcomacat@mail.com"