baseURL = "https://example.com"
languageCode = "en-us"
title = "2bcoma dev studio"
theme = "main"
copyright = "2bcoma"

[params]
  avatar = "https://openclipart.org/download/103855/tux.svg"
  info = """
  We are passion and progressive indie dev studio.
  We love to develop multiplatform applications.
  """

[[menu.main]]
  name = "Home"
  url = "/"

[[menu.main]]
  name = "Our Apps"
  url = "/apps"

[[params.social]]
  name = "tiktok"
  url = "https://vm.tiktok.com/ZS5gXNh7/"

[[params.social]]
  name = "instagram"
  url = "https://instagram.com/2bcoma?igshid=mm9sg7ctjx0m"

[[params.social]]
  name = "github"
  url = "https://github.com/2bcoma"

[[params.social]]
  name = "email"
  url = "mailto:bbcoma@mail.com"